"""empty message

Revision ID: 09be73b6689f
Revises: 33174fc2675a
Create Date: 2021-04-29 18:37:48.361907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09be73b6689f'
down_revision = '33174fc2675a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'registered_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'registered_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
